### ISSUE TITLE
Badge component 

### ISSUE THREAD

**Issue by tranguv** [tranguv/NutriTracker#32]
<img width="411" alt="image" src="https://github.com/tranguv/NutriTracker/assets/89886131/730def20-5f8a-4f9f-94c6-08e36c919822">

Resources:
TBD

**Comment by Frisb33** [comment]
Finish the traversing back and forth feature with a customizable number of icons. UI design is being implemented according Figma's prototype
![badgeunfinished](https://github.com/tranguv/NutriTracker/assets/92132623/9c9d2d4b-e5d9-4ae1-a96a-35eb7d887481)
type

**Comment by Frisb33** [comment]
Done fixing react icons, badge container is completed
![badgeunfinished](https://github.com/tranguv/NutriTracker/assets/92132623/2ee48851-a7af-49bd-bc7d-102f1bc5d23c)
